[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "mfhq-scripts"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "opencv-python",
    "numpy",
    "pyautogui",
    "pywin32; platform_system == 'Windows'",
    "playsound==1.2.2",
    "pynput",
    "Pillow",
]

[project.optional-dependencies]
build = [
    "pyinstaller",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
common = ["photo/*"]
